services:
  - type: web
    name: viralink
    env: docker
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
      php artisan storage:link
    startCommand: apache2-foreground
    envVars:
      - key: APP_NAME
        value: ViraLink
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        value: https://viralink.onrender.com
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: sql.freedb.tech
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: freedb_virallink
      - key: DB_USERNAME
        value: freedb_zyron
      - key: DB_PASSWORD
        value: BXKN8n#m5ezNKa%
      - key: BROADCAST_DRIVER
        value: log
      - key: CACHE_DRIVER
        value: file
      - key: FILESYSTEM_DISK
        value: local
      - key: QUEUE_CONNECTION
        value: sync
      - key: SESSION_DRIVER
        value: file
      - key: SESSION_LIFETIME
        value: "120"
